name: Build SecureMessenger EXE

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: SecureMessenger.sln  # Naziv rešenja (.sln)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Dependencies
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=Release /p:Platform="Any CPU"

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SecureMessenger EXE
        path: |
          **\bin\Release\**\*.exe
